apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: k8snorootcontainers
spec:
  crd:
    spec:
      names:
        kind: K8sNoRootContainers
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8snorootcontainers
        violation[{"msg": msg}] {
          c := input.review.object.spec.containers[_]
          c.securityContext.runAsUser == 0
          msg := sprintf("BLOCKED: Container '%v' runs as root (UID 0)", [c.name])
        }
